-- Phase 1: per-user tasks with Row-Level Security + 100-task limit
-- Run this in the Supabase dashboard SQL editor (or via `supabase db push`).

-- 1. Ensure the todos table has user scoping ---------------------------------
-- (If the table already exists from earlier demo use, these ADD COLUMNs are
--  idempotent thanks to IF NOT EXISTS.)
create table if not exists public.todos (
  id          bigint generated by default as identity primary key,
  text        text not null,
  date        date,
  category    text default 'General',
  completed   boolean default false
);

alter table public.todos
  add column if not exists user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade;

alter table public.todos
  add column if not exists created_at timestamptz not null default now();

create index if not exists todos_user_id_idx on public.todos (user_id);

-- 2. Row-Level Security ------------------------------------------------------
alter table public.todos enable row level security;

drop policy if exists "todos_select_own" on public.todos;
create policy "todos_select_own" on public.todos
  for select using (auth.uid() = user_id);

drop policy if exists "todos_insert_own" on public.todos;
create policy "todos_insert_own" on public.todos
  for insert with check (auth.uid() = user_id);

drop policy if exists "todos_update_own" on public.todos;
create policy "todos_update_own" on public.todos
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "todos_delete_own" on public.todos;
create policy "todos_delete_own" on public.todos
  for delete using (auth.uid() = user_id);

-- 3. Per-user task limit (100) ----------------------------------------------
create or replace function public.enforce_task_limit()
returns trigger
language plpgsql
as $$
declare
  task_count int;
begin
  select count(*) into task_count
    from public.todos
   where user_id = new.user_id;

  if task_count >= 100 then
    raise exception 'TASK_LIMIT' using hint = 'Free plan is limited to 100 tasks.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enforce_task_limit on public.todos;
create trigger trg_enforce_task_limit
  before insert on public.todos
  for each row execute function public.enforce_task_limit();
